services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: academico
    ports:
      - "4040:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/db.sql:/docker-entrypoint-initdb.d/01-init.sql

volumes:
  mysql_data: